### ISSUE TITLE
Go get crashes

### ISSUE THREAD

**Issue by julisch94** [dasfoo/i2c#12]
Hey there,
I am trying to use your library but when I run `go get github.com/dasfoo/i2c` the following error occurs:

    > go get -v github.com/dasfoo/i2c
    github.com/dasfoo/i2c
    # github.com/dasfoo/i2c
    ../../dasfoo/i2c/i2c.go:7:11: fatal error: '/usr/include/linux/i2c-dev.h' file not found
     #include "/usr/include/linux/i2c-dev.h"
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

Why can't I go get your library here?

**Comment by dotdoom** [comment]
Hi there Julian,

thank you for the feedback! Apparently I didn't update the repository with installation steps, sorry about that. On Debian / Ubuntu, an additional header file is needed, which can be installed via `sudo apt-get install libi2c-dev`.

Let me know if this helps, I'm updating README file right now.

**Comment by julisch94** [comment]
Thanks for your help!
